<a href="https://colab.research.google.com/github/reddragon72q/ai-test-questions/blob/main/AI_test_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A random sample of 100 men is taken and their mean height is found to be 180 cm. The population variance is 36 cm2. Find the 95% confidence interval for the mean height of the population (μ).

Answer choices

Select only one option

(179.648, 183.760)

(178.248, 188.719)

(177.124, 180.178)

(178.824, 181.176)

Answer is (178.824, 181.176)

In [1]:
import numpy as np
from  scipy.stats import norm
np.round(norm.interval(0.95, loc = 180, scale = 6/np.sqrt(100)), 3)

array([178.824, 181.176])

___________________________________________________________________________________________________________________

A landlord wants to rent an unfurnished one-bedroom apartment in Chicago. The mean monthly rent for a random sample of 100 apartments advertised on a website that lists apartments in Chicago for rent is $1000.

Assume a population standard deviation of $200. What is the 95% confidence interval for the mean rent?

Answer choices

Select only one option

(960.8, 1039.2)

(968.1, 1032.1)

(961.8, 1038.2)

(965.5, 1035.5)

Answer is (960.8, 1039.2)

In [2]:
from scipy.stats import norm
import numpy as np
np.round(norm.interval(0.95, loc = 1000, scale = 200/np.sqrt(100)), 1)

array([ 960.8, 1039.2])

___________________________________________________________________________________________________________________

A survey of females aged 16-60 years was conducted by the Department of Population Censuses (DPC). It was found that a sample of fifty female students has a mean height of 160.9 cm with a standard deviation of 6 cm.

Determine the confidence interval of height with a confidence level of 95% and conclude whether their heights are typical to the general population.

Answer choices

Select only one option

(157.24, 161.56) - Heights are typical to the general population

(159.19, 162.61) - Heights are typical to the general population

(158.24, 160.36) - Heights are typical to the general population

(150, 162) - Heights are typical to the general population

Answer is (159.19, 162.61)

In [3]:
from scipy.stats import t
import numpy as np
np.round(t.interval(0.95, df = 50-1, loc = 160.9, scale = 6/np.sqrt(50)), 2)

array([159.19, 162.61])

___________________________________________________________________________________________________________________